### ISSUE TITLE
Make DeterminePrefix more efficient 

### ISSUE THREAD

**Issue by Finlay-Mitchell** [Finlay-Mitchell/FinBot#5]
Where it is referenced more than once in a function, set a variable to the prefix to make it faster.

**Comment by TGWaffles** [comment]
What about a global dictionary that you fill up and access it from the dictionary first, and only make a db request if it's not present in the dictionary?

Remember also that you'd have to update the dictionary when they change their prefix, too, but that shouldn't be a problem

**Comment by Finlay-Mitchell** [comment]
> What about a global dictionary that you fill up and access it from the dictionary first, and only make a db request if it's not present in the dictionary?
> 
> Remember also that you'd have to update the dictionary when they change their prefix, too, but that shouldn't be a problem.
> 
> Would be guild id (key) mapped to prefix (value).

Hmmmm, will implement that soon!
